version: '3'

services:
  main_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./uuid-ossp.sql:/docker-entrypoint-initdb.d/uuid-ossp.sql

  test_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${TEST_POSTGRES_DB}
      POSTGRES_USER: ${TEST_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TEST_POSTGRES_PASSWORD}
    ports:
      - "${TEST_POSTGRES_PORT}:5432"
    volumes:
      - ./uuid-ossp.sql:/docker-entrypoint-initdb.d/uuid-ossp.sql