version: '3'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./uuid-ossp.sql:/docker-entrypoint-initdb.d/uuid-ossp.sql
    container_name: database

  server:
    build: .
    command: sh -c "python app/initial_data.py && uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
    #    command: sh -c "alembic upgrade head && python app/initial_data.py && uvicorn app.main:app --reload --port 8000 --host 0.0.0.0"
    ports:
      - 8000:8000
    depends_on:
      - database
