version: '3'

services:
  postgres:
    image: postgres:latest
    env_file: '.env'
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./uuid-ossp.sql:/docker-entrypoint-initdb.d/uuid-ossp.sql