"""review to profile

Revision ID: c308228b7b0e
Revises: 597bdd92b551
Create Date: 2023-10-25 16:33:19.931979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c308228b7b0e'
down_revision: Union[str, None] = '597bdd92b551'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('profile_id', sa.Uuid(), nullable=False))
    op.drop_constraint('review_user_id_fkey', 'review', type_='foreignkey')
    op.create_foreign_key(None, 'review', 'profile', ['profile_id'], ['id'])
    op.drop_column('review', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.create_foreign_key('review_user_id_fkey', 'review', 'user', ['user_id'], ['id'])
    op.drop_column('review', 'profile_id')
    # ### end Alembic commands ###
