"""add update image

Revision ID: 288bf50416de
Revises: 1e90c1400dce
Create Date: 2023-11-01 02:07:09.298211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '288bf50416de'
down_revision: Union[str, None] = '1e90c1400dce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('name', sa.String(), nullable=False))
    op.add_column('image', sa.Column('format', sa.String(), nullable=False))
    op.drop_column('image', 'width')
    op.drop_column('image', 'height')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('image', sa.Column('width', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('image', 'format')
    op.drop_column('image', 'name')
    # ### end Alembic commands ###
