"""update product

Revision ID: 1fb40cbf8887
Revises: e33e4ad216d0
Create Date: 2023-11-05 21:42:45.032680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fb40cbf8887'
down_revision: Union[str, None] = 'e33e4ad216d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'image_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'image_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
