"""update order_item

Revision ID: f544e13ec113
Revises: aba234a54289
Create Date: 2023-11-06 21:14:50.373558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f544e13ec113'
down_revision: Union[str, None] = 'aba234a54289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_item_order_id_fkey', 'order_item', type_='foreignkey')
    op.create_foreign_key(None, 'order_item', 'order', ['order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_item', type_='foreignkey')
    op.create_foreign_key('order_item_order_id_fkey', 'order_item', 'order', ['order_id'], ['id'])
    # ### end Alembic commands ###
