"""update Order

Revision ID: 361bb26cf42b
Revises: 1fb40cbf8887
Create Date: 2023-11-06 01:09:30.323592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '361bb26cf42b'
down_revision: Union[str, None] = '1fb40cbf8887'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('number', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_constraint('order_name_key', 'order', type_='unique')
    op.create_unique_constraint(None, 'order', ['number'])
    op.drop_column('order', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'order', type_='unique')
    op.create_unique_constraint('order_name_key', 'order', ['name'])
    op.drop_column('order', 'number')
    # ### end Alembic commands ###
